import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "ik_language";

const dictionaries = {
  en: {
    navExplore: "Explore",
    navDiscover: "Discover",
    navItinerary: "Itinerary",
    navSaved: "Saved",
    navMap: "Map",
    navProfile: "Profile",
    navDashboard: "Overview",
    navApprovals: "Approvals",
    navListings: "Manage Places",
    navSubmitPlace: "Add Place",
    navMySubmissions: "My Submissions",
    navAnalytics: "Insights",
    navUsers: "Users",
    navSettings: "Settings",
    logout: "Logout",
    greeting: "Namaste",
    explorer: "Explorer",
    greetingSubtitle: "Discover the soul of Karnataka through local experiences.",
    useMyLocation: "Use my location",
    locationActive: "Location active",
    locationUnavailable: "Location unavailable",
    locating: "Locating...",
    adminWorkspace: "Admin workspace",
    featuredDiscoveries: "Featured Discoveries",
    showAll: "Show all",
    aiGuideTitle: "AI Itinerary Guide",
    aiGuideText: "Let our AI plan your perfect Karnataka weekend getaway based on your interests.",
    profileTitle: "Your Profile",
    profileSubtitle: "Manage your account, saved journeys, and language preferences.",
    accountOverview: "Account Overview",
    savedPlaces: "Saved Places",
    role: "Role",
    language: "Language",
    quickActions: "Quick Actions",
    settings: "Settings",
    notifications: "Notifications",
    travelStyle: "Travel Style",
    signOut: "Sign out",
    itineraryTitle: "Build Your Itinerary",
    itinerarySubtitle: "Choose a district and interests, then we will shape a route around them.",
    chooseDistrict: "Choose district",
    howManyDays: "How many days?",
    preferredCategories: "Preferred categories",
    generatePlan: "Generate Day Plan",
    generatingPlan: "Generating...",
    pickDistrictError: "Choose a district.",
    profileSavedCount: "saved places",
    profileSettingsHint: "Notifications and travel preferences can be expanded next.",
    mapLocationError: "Enable location access to center the map around you.",
    centerOnMe: "Center on me",
    listingsTitle: "Discover",
    listingsSubtitle: "Browse curated places and businesses.",
    discoverSearchTitle: "Discover Search",
    discoverSearchPlaceholder: "Search by place, category, address...",
    savedPlacesTitle: "Saved Places",
    noSavedPlaces: "No saved places yet.",
    interactiveMapTitle: "Interactive Map",
    filter: "Filter",
    all: "All",
    category: "Category",
    district: "District",
    refresh: "Refresh",
    clear: "Clear",
    openDetails: "Open Details",
    directions: "Directions",
    placeDetailTitle: "Place Detail",
    placeDetailsFallback: "Place Details",
    categoryLabel: "Category",
    ratingLabel: "Rating",
    noDescription: "No description available yet.",
    restaurantDetails: "Restaurant Details",
    stayDetails: "Stay Details",
    cuisine: "Cuisine",
    price: "Price",
    mustTry: "Must try",
    type: "Type",
    pricePerNight: "Price/night",
    amenities: "Amenities",
    photos: "Photos",
    noPhotos: "No photos added yet.",
    addYourPhoto: "Add Your Photo",
    addYourPhotoHint: "You can suggest more photos for this place. Admin approval is required before they appear publicly.",
    uploadPhoto: "Uploading photo...",
    submitApproval: "Submitting for approval...",
    photoSubmitted: "Photo submitted for admin approval.",
    videos: "Videos",
    noVideos: "No videos added yet.",
    addYourVideo: "Add Your Video",
    addYourVideoHint: "You can suggest more videos for this place. Admin approval is required before they appear publicly.",
    uploadVideo: "Uploading video...",
    submitVideoApproval: "Submitting video for approval...",
    videoSubmitted: "Video submitted for admin approval.",
    removeFromSaved: "Remove from Saved",
    savePlace: "Save Place",
    addToItinerary: "Add to Itinerary",
    getDirections: "Get Directions",
    readReviews: "Read Reviews",
    photoSubmittedAlertTitle: "Photo Submitted",
    photoSubmittedAlertBody: "Your photo was sent for admin approval.",
    videoSubmittedAlertTitle: "Video Submitted",
    videoSubmittedAlertBody: "Your video was sent for admin approval.",
    savedAlertTitle: "Saved",
    saveFailed: "Failed to save this place. Please try again.",
    directionsAlertTitle: "Directions",
    noCoordinates: "No coordinates available for this place yet.",
    itineraryAlertTitle: "Itinerary",
    missingDistrict: "District is missing for this place.",
    itineraryFailed: "Unable to add to itinerary.",
    distanceUnknown: "Distance unknown",
    kmAway: "km away",
    photoWord: "photo",
    photosWord: "photos",
    videoWord: "video",
    videosWord: "videos",
    noPhoto: "No photo",
    videoAvailable: "Video available",
    imageUnavailable: "Image unavailable",
    videoUnavailable: "Video unavailable",
    categoryRestaurant: "Restaurant",
    categoryGenerationalShop: "Generational Shop",
    categoryTouristPlace: "Tourist Place",
    categoryHiddenGem: "Hidden Gem",
    categoryStay: "Stay",
  },
  kn: {
    navExplore: "ಅನ್ವೇಷಿಸಿ",
    navDiscover: "ಹುಡುಕಿ",
    navItinerary: "ಪ್ರವಾಸ ಯೋಜನೆ",
    navSaved: "ಉಳಿಸಿದವು",
    navMap: "ನಕ್ಷೆ",
    navProfile: "ಪ್ರೊಫೈಲ್",
    navDashboard: "ಅವಲೋಕನ",
    navApprovals: "ಅನುಮೋದನೆಗಳು",
    navListings: "ಸ್ಥಳ ನಿರ್ವಹಣೆ",
    navSubmitPlace: "ಸ್ಥಳ ಸೇರಿಸಿ",
    navMySubmissions: "ನನ್ನ ಸಲ್ಲಿಕೆಗಳು",
    navAnalytics: "ಅವಲೋಕನೆಗಳು",
    navUsers: "ಬಳಕೆದಾರರು",
    navSettings: "ಸೆಟ್ಟಿಂಗ್ಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",
    greeting: "ನಮಸ್ತೆ",
    explorer: "ಅನ್ವೇಷಕ",
    greetingSubtitle: "ಸ್ಥಳೀಯ ಅನುಭವಗಳ ಮೂಲಕ ಕರ್ನಾಟಕದ ಆತ್ಮವನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.",
    useMyLocation: "ನನ್ನ ಸ್ಥಳ ಬಳಸಿ",
    locationActive: "ಸ್ಥಳ ಸಕ್ರಿಯ",
    locationUnavailable: "ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ",
    locating: "ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    adminWorkspace: "ಆಡ್ಮಿನ್ ಕಾರ್ಯಕ್ಷೇತ್ರ",
    featuredDiscoveries: "ಮುಖ್ಯ ಅನ್ವೇಷಣೆಗಳು",
    showAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    aiGuideTitle: "ಎಐ ಪ್ರವಾಸ ಮಾರ್ಗದರ್ಶಿ",
    aiGuideText: "ನಿಮ್ಮ ಆಸಕ್ತಿಗಳ ಆಧಾರದ ಮೇಲೆ ಕರ್ನಾಟಕದ ಪರಿಪೂರ್ಣ ವೀಕೆಂಡ್ ಪ್ರವಾಸವನ್ನು ನಾವು ರೂಪಿಸುತ್ತೇವೆ.",
    profileTitle: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್",
    profileSubtitle: "ನಿಮ್ಮ ಖಾತೆ, ಉಳಿಸಿದ ಪ್ರವಾಸಗಳು ಮತ್ತು ಭಾಷಾ ಆಯ್ಕೆಯನ್ನು ನಿರ್ವಹಿಸಿ.",
    accountOverview: "ಖಾತೆ ಅವಲೋಕನ",
    savedPlaces: "ಉಳಿಸಿದ ಸ್ಥಳಗಳು",
    role: "ಪಾತ್ರ",
    language: "ಭಾಷೆ",
    quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್ಗಳು",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    travelStyle: "ಪ್ರವಾಸ ಶೈಲಿ",
    signOut: "ಲಾಗ್ ಔಟ್",
    itineraryTitle: "ನಿಮ್ಮ ಪ್ರವಾಸ ಯೋಜನೆ ರೂಪಿಸಿ",
    itinerarySubtitle: "ಜಿಲ್ಲೆ ಮತ್ತು ಆಸಕ್ತಿಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ, ನಾವು ಮಾರ್ಗವನ್ನು ರೂಪಿಸುತ್ತೇವೆ.",
    chooseDistrict: "ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ",
    howManyDays: "ಎಷ್ಟು ದಿನಗಳು?",
    preferredCategories: "ಇಷ್ಟದ ವರ್ಗಗಳು",
    generatePlan: "ಯೋಜನೆ ರಚಿಸಿ",
    generatingPlan: "ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    pickDistrictError: "ದಯವಿಟ್ಟು ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    profileSavedCount: "ಉಳಿಸಿದ ಸ್ಥಳಗಳು",
    profileSettingsHint: "ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಪ್ರವಾಸ ಆಯ್ಕೆಗಳನ್ನು ಮುಂದೆ ವಿಸ್ತರಿಸಬಹುದು.",
    mapLocationError: "ನಕ್ಷೆಯನ್ನು ನಿಮ್ಮ ಸುತ್ತ ಕೇಂದ್ರಗೊಳಿಸಲು ಸ್ಥಳ ಅನುಮತಿಸಿ.",
    centerOnMe: "ನನ್ನ ಮೇಲೆ ಕೇಂದ್ರಗೊಳಿಸಿ",
    listingsTitle: "ಹುಡುಕಿ",
    listingsSubtitle: "ಆಯ್ಕೆಮಾಡಿದ ಸ್ಥಳಗಳು ಮತ್ತು ವ್ಯವಹಾರಗಳನ್ನು ವೀಕ್ಷಿಸಿ.",
    discoverSearchTitle: "ಹುಡುಕಾಟ",
    discoverSearchPlaceholder: "ಸ್ಥಳ, ವರ್ಗ, ವಿಳಾಸ ಮೂಲಕ ಹುಡುಕಿ...",
    savedPlacesTitle: "ಉಳಿಸಿದ ಸ್ಥಳಗಳು",
    noSavedPlaces: "ಇನ್ನೂ ಯಾವುದೇ ಸ್ಥಳ ಉಳಿಸಲಾಗಿಲ್ಲ.",
    interactiveMapTitle: "ಸಂವಾದಾತ್ಮಕ ನಕ್ಷೆ",
    filter: "ಫಿಲ್ಟರ್",
    all: "ಎಲ್ಲಾ",
    category: "ವರ್ಗ",
    district: "ಜಿಲ್ಲೆ",
    refresh: "ರಿಫ್ರೆಶ್",
    clear: "ತೆರವುಗೊಳಿಸಿ",
    openDetails: "ವಿವರಗಳನ್ನು ತೆರೆಯಿರಿ",
    directions: "ದಿಕ್ಕುಗಳು",
    placeDetailTitle: "ಸ್ಥಳ ವಿವರ",
    placeDetailsFallback: "ಸ್ಥಳದ ವಿವರಗಳು",
    categoryLabel: "ವರ್ಗ",
    ratingLabel: "ರೇಟಿಂಗ್",
    noDescription: "ಇನ್ನೂ ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ.",
    restaurantDetails: "ಉಪಹಾರ ಗೃಹದ ವಿವರಗಳು",
    stayDetails: "ವಾಸ್ತವ್ಯದ ವಿವರಗಳು",
    cuisine: "ಅಡುಗೆ ಶೈಲಿ",
    price: "ಬೆಲೆ",
    mustTry: "ಖಂಡಿತ ಪ್ರಯತ್ನಿಸಿ",
    type: "ಪ್ರಕಾರ",
    pricePerNight: "ಪ್ರತಿ ರಾತ್ರಿಯ ಬೆಲೆ",
    amenities: "ಸೌಲಭ್ಯಗಳು",
    photos: "ಫೋಟೋಗಳು",
    noPhotos: "ಇನ್ನೂ ಫೋಟೋಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.",
    addYourPhoto: "ನಿಮ್ಮ ಫೋಟೋ ಸೇರಿಸಿ",
    addYourPhotoHint: "ಈ ಸ್ಥಳಕ್ಕೆ ನೀವು ಇನ್ನಷ್ಟು ಫೋಟೋಗಳನ್ನು ಸೂಚಿಸಬಹುದು. ಸಾರ್ವಜನಿಕವಾಗಿ ಕಾಣಿಸುವ ಮೊದಲು ಆಡ್ಮಿನ್ ಅನುಮೋದನೆ ಅಗತ್ಯ.",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    submitApproval: "ಅನುಮೋದನೆಗಾಗಿ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    photoSubmitted: "ಫೋಟೋ ಆಡ್ಮಿನ್ ಅನುಮೋದನೆಗಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.",
    videos: "ವೀಡಿಯೊಗಳು",
    noVideos: "ಇನ್ನೂ ವೀಡಿಯೊಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.",
    addYourVideo: "ನಿಮ್ಮ ವೀಡಿಯೊ ಸೇರಿಸಿ",
    addYourVideoHint: "ಈ ಸ್ಥಳಕ್ಕೆ ನೀವು ಇನ್ನಷ್ಟು ವೀಡಿಯೊಗಳನ್ನು ಸೂಚಿಸಬಹುದು. ಸಾರ್ವಜನಿಕವಾಗಿ ಕಾಣಿಸುವ ಮೊದಲು ಆಡ್ಮಿನ್ ಅನುಮೋದನೆ ಅಗತ್ಯ.",
    uploadVideo: "ವೀಡಿಯೊ ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    submitVideoApproval: "ವೀಡಿಯೊ ಅನುಮೋದನೆಗಾಗಿ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    videoSubmitted: "ವೀಡಿಯೊ ಆಡ್ಮಿನ್ ಅನುಮೋದನೆಗಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.",
    removeFromSaved: "ಉಳಿಸಿದುದರಿಂದ ತೆಗೆದುಹಾಕಿ",
    savePlace: "ಸ್ಥಳವನ್ನು ಉಳಿಸಿ",
    addToItinerary: "ಪ್ರವಾಸ ಯೋಜನೆಗೆ ಸೇರಿಸಿ",
    getDirections: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ",
    readReviews: "ವಿಮರ್ಶೆಗಳು ಓದಿ",
    photoSubmittedAlertTitle: "ಫೋಟೋ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    photoSubmittedAlertBody: "ನಿಮ್ಮ ಫೋಟೋ ಆಡ್ಮಿನ್ ಅನುಮೋದನೆಗಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
    videoSubmittedAlertTitle: "ವೀಡಿಯೊ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    videoSubmittedAlertBody: "ನಿಮ್ಮ ವೀಡಿಯೊ ಆಡ್ಮಿನ್ ಅನುಮೋದನೆಗಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
    savedAlertTitle: "ಉಳಿಸಲಾಗಿದೆ",
    saveFailed: "ಈ ಸ್ಥಳವನ್ನು ಉಳಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    directionsAlertTitle: "ದಿಕ್ಕುಗಳು",
    noCoordinates: "ಈ ಸ್ಥಳಕ್ಕೆ ಇನ್ನೂ ನಿರ್ದಿಷ್ಟ ಸಂಯೋಜನೆಗಳು ಲಭ್ಯವಿಲ್ಲ.",
    itineraryAlertTitle: "ಪ್ರವಾಸ ಯೋಜನೆ",
    missingDistrict: "ಈ ಸ್ಥಳಕ್ಕೆ ಜಿಲ್ಲೆ ಮಾಹಿತಿ ಕಾಣೆಯಾಗಿದೆ.",
    itineraryFailed: "ಪ್ರವಾಸ ಯೋಜನೆಗೆ ಸೇರಿಸಲಾಗಲಿಲ್ಲ.",
    distanceUnknown: "ದೂರ ತಿಳಿದಿಲ್ಲ",
    kmAway: "ಕಿ.ಮೀ ದೂರ",
    photoWord: "ಫೋಟೋ",
    photosWord: "ಫೋಟೋಗಳು",
    videoWord: "ವೀಡಿಯೊ",
    videosWord: "ವೀಡಿಯೊಗಳು",
    noPhoto: "ಫೋಟೋ ಇಲ್ಲ",
    videoAvailable: "ವೀಡಿಯೊ ಲಭ್ಯವಿದೆ",
    imageUnavailable: "ಚಿತ್ರ ಲಭ್ಯವಿಲ್ಲ",
    videoUnavailable: "ವೀಡಿಯೊ ಲಭ್ಯವಿಲ್ಲ",
    categoryRestaurant: "ಉಪಹಾರ ಗೃಹ",
    categoryGenerationalShop: "ಪಾರಂಪರಿಕ ಅಂಗಡಿ",
    categoryTouristPlace: "ಪ್ರವಾಸಿ ಸ್ಥಳ",
    categoryHiddenGem: "ಮರೆವಿನ ಮಣಿ",
    categoryStay: "ವಾಸ್ತವ್ಯ",
  },
  hi: {
    navExplore: "एक्सप्लोर",
    navDiscover: "डिस्कवर",
    navItinerary: "यात्रा योजना",
    navSaved: "सेव्ड",
    navMap: "मैप",
    navProfile: "प्रोफाइल",
    navDashboard: "ओवरव्यू",
    navApprovals: "अप्रूवल",
    navListings: "प्लेस प्रबंधन",
    navSubmitPlace: "प्लेस जोड़ें",
    navMySubmissions: "मेरी सबमिशन",
    navAnalytics: "इनसाइट्स",
    navUsers: "यूज़र्स",
    navSettings: "सेटिंग्स",
    logout: "लॉग आउट",
    greeting: "नमस्ते",
    explorer: "एक्सप्लोरर",
    greetingSubtitle: "स्थानीय अनुभवों के साथ कर्नाटक की असली पहचान खोजिए।",
    useMyLocation: "मेरा लोकेशन इस्तेमाल करें",
    locationActive: "लोकेशन सक्रिय",
    locationUnavailable: "लोकेशन उपलब्ध नहीं",
    locating: "लोकेशन खोजी जा रही है...",
    adminWorkspace: "एडमिन वर्कस्पेस",
    featuredDiscoveries: "फ़ीचर्ड डिस्कवरी",
    showAll: "सब देखें",
    aiGuideTitle: "एआई यात्रा गाइड",
    aiGuideText: "आपकी पसंद के आधार पर हम कर्नाटक का शानदार वीकेंड प्लान तैयार करेंगे।",
    profileTitle: "आपकी प्रोफाइल",
    profileSubtitle: "अपना अकाउंट, सेव्ड ट्रिप्स और भाषा सेटिंग्स संभालें।",
    accountOverview: "अकाउंट ओवरव्यू",
    savedPlaces: "सेव्ड प्लेसेस",
    role: "रोल",
    language: "भाषा",
    quickActions: "क्विक एक्शंस",
    settings: "सेटिंग्स",
    notifications: "नोटिफिकेशन",
    travelStyle: "ट्रैवल स्टाइल",
    signOut: "लॉग आउट",
    itineraryTitle: "अपनी यात्रा योजना बनाएं",
    itinerarySubtitle: "जिला और रुचियां चुनिए, हम उसी हिसाब से प्लान बनाएंगे।",
    chooseDistrict: "जिला चुनें",
    howManyDays: "कितने दिन?",
    preferredCategories: "पसंदीदा कैटेगरी",
    generatePlan: "डे प्लान बनाएं",
    generatingPlan: "बनाया जा रहा है...",
    pickDistrictError: "कृपया एक जिला चुनें।",
    profileSavedCount: "सेव्ड प्लेसेस",
    profileSettingsHint: "नोटिफिकेशन और ट्रैवल प्रेफरेंस को आगे और बेहतर किया जा सकता है।",
    mapLocationError: "मैप को आपकी जगह पर केंद्रित करने के लिए लोकेशन अनुमति दें।",
    centerOnMe: "मेरे ऊपर केंद्रित करें",
    listingsTitle: "डिस्कवर",
    listingsSubtitle: "क्यूरेटेड जगहों और व्यवसायों को देखें।",
    discoverSearchTitle: "डिस्कवर सर्च",
    discoverSearchPlaceholder: "जगह, कैटेगरी, पता से खोजें...",
    savedPlacesTitle: "सेव्ड प्लेसेस",
    noSavedPlaces: "अभी तक कोई सेव्ड प्लेस नहीं है।",
    interactiveMapTitle: "इंटरएक्टिव मैप",
    filter: "फ़िल्टर",
    all: "सभी",
    category: "कैटेगरी",
    district: "जिला",
    refresh: "रीफ्रेश",
    clear: "साफ़ करें",
    openDetails: "डिटेल्स खोलें",
    directions: "दिशाएं",
    placeDetailTitle: "प्लेस डिटेल",
    placeDetailsFallback: "प्लेस डिटेल्स",
    categoryLabel: "कैटेगरी",
    ratingLabel: "रेटिंग",
    noDescription: "अभी कोई विवरण उपलब्ध नहीं है।",
    restaurantDetails: "रेस्टोरेंट डिटेल्स",
    stayDetails: "स्टे डिटेल्स",
    cuisine: "क्यूज़ीन",
    price: "कीमत",
    mustTry: "ज़रूर ट्राय करें",
    type: "प्रकार",
    pricePerNight: "प्रति रात कीमत",
    amenities: "सुविधाएं",
    photos: "फोटो",
    noPhotos: "अभी तक कोई फोटो नहीं जोड़ा गया।",
    addYourPhoto: "अपना फोटो जोड़ें",
    addYourPhotoHint: "आप इस जगह के लिए और फोटो सुझा सकते हैं। सार्वजनिक रूप से दिखने से पहले एडमिन की मंज़ूरी ज़रूरी है।",
    uploadPhoto: "फोटो अपलोड हो रहा है...",
    submitApproval: "मंज़ूरी के लिए भेजा जा रहा है...",
    photoSubmitted: "फोटो एडमिन मंज़ूरी के लिए भेज दिया गया है।",
    videos: "वीडियो",
    noVideos: "अभी तक कोई वीडियो नहीं जोड़ा गया।",
    addYourVideo: "अपना वीडियो जोड़ें",
    addYourVideoHint: "आप इस जगह के लिए और वीडियो सुझा सकते हैं। सार्वजनिक रूप से दिखने से पहले एडमिन की मंज़ूरी ज़रूरी है।",
    uploadVideo: "वीडियो अपलोड हो रहा है...",
    submitVideoApproval: "वीडियो मंज़ूरी के लिए भेजा जा रहा है...",
    videoSubmitted: "वीडियो एडमिन मंज़ूरी के लिए भेज दिया गया है।",
    removeFromSaved: "सेव्ड से हटाएं",
    savePlace: "प्लेस सेव करें",
    addToItinerary: "यात्रा योजना में जोड़ें",
    getDirections: "दिशाएं पाएं",
    readReviews: "रिव्यू पढ़ें",
    photoSubmittedAlertTitle: "फोटो सबमिट हुआ",
    photoSubmittedAlertBody: "आपका फोटो एडमिन मंज़ूरी के लिए भेजा गया है।",
    videoSubmittedAlertTitle: "वीडियो सबमिट हुआ",
    videoSubmittedAlertBody: "आपका वीडियो एडमिन मंज़ूरी के लिए भेजा गया है।",
    savedAlertTitle: "सेव्ड",
    saveFailed: "इस जगह को सेव नहीं किया जा सका। फिर से कोशिश करें।",
    directionsAlertTitle: "दिशाएं",
    noCoordinates: "इस जगह के लिए अभी निर्देशांक उपलब्ध नहीं हैं।",
    itineraryAlertTitle: "यात्रा योजना",
    missingDistrict: "इस जगह के लिए जिला जानकारी उपलब्ध नहीं है।",
    itineraryFailed: "यात्रा योजना में जोड़ना संभव नहीं हुआ।",
    distanceUnknown: "दूरी अज्ञात",
    kmAway: "कि.मी. दूर",
    photoWord: "फोटो",
    photosWord: "फोटो",
    videoWord: "वीडियो",
    videosWord: "वीडियो",
    noPhoto: "कोई फोटो नहीं",
    videoAvailable: "वीडियो उपलब्ध है",
    imageUnavailable: "इमेज उपलब्ध नहीं है",
    videoUnavailable: "वीडियो उपलब्ध नहीं है",
    categoryRestaurant: "रेस्टोरेंट",
    categoryGenerationalShop: "पीढ़ीगत दुकान",
    categoryTouristPlace: "पर्यटन स्थल",
    categoryHiddenGem: "छुपा हुआ रत्न",
    categoryStay: "स्टे",
  },
};

const LanguageContext = createContext({
  language: "en",
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
});

function getInitialLanguage() {
  if (typeof localStorage === "undefined") {
    return "en";
  }
  return localStorage.getItem(STORAGE_KEY) || "en";
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    if (typeof localStorage === "undefined") {
      return;
    }
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key, fallback) => dictionaries[language]?.[key] || dictionaries.en[key] || fallback || key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
